// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBudvH8jpN-E8_BpmGha7Ql7quM_NJJMpw',
    appId: '1:262304244604:web:d87d2d8292ac981abbfaf9',
    messagingSenderId: '262304244604',
    projectId: 'weight-tracker-be0d4',
    authDomain: 'weight-tracker-be0d4.firebaseapp.com',
    storageBucket: 'weight-tracker-be0d4.appspot.com',
    measurementId: 'G-F5M1D64VN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsnC_j-DJUl89Zy2IYStbjwXO75CRBh54',
    appId: '1:262304244604:android:12bc8c1ed8fc711dbbfaf9',
    messagingSenderId: '262304244604',
    projectId: 'weight-tracker-be0d4',
    storageBucket: 'weight-tracker-be0d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy_ghvWmO999yCGYG7oY4mls1AEVh_AfU',
    appId: '1:262304244604:ios:e2fa961434842350bbfaf9',
    messagingSenderId: '262304244604',
    projectId: 'weight-tracker-be0d4',
    storageBucket: 'weight-tracker-be0d4.appspot.com',
    iosClientId: '262304244604-ke3jo6e91b170khedu3t9lnnggk8emil.apps.googleusercontent.com',
    iosBundleId: 'com.example.weightTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy_ghvWmO999yCGYG7oY4mls1AEVh_AfU',
    appId: '1:262304244604:ios:e2fa961434842350bbfaf9',
    messagingSenderId: '262304244604',
    projectId: 'weight-tracker-be0d4',
    storageBucket: 'weight-tracker-be0d4.appspot.com',
    iosClientId: '262304244604-ke3jo6e91b170khedu3t9lnnggk8emil.apps.googleusercontent.com',
    iosBundleId: 'com.example.weightTracker',
  );
}
